[album]
album_id = "bb4c24e8-fbe1-4fb8-a8ff-bafe4c1422c0"
title = "『劇場版 ヴァイオレット・エヴァーガーデン』オリジナル・サウンドトラック「VIOLET EVERGARDEN : Echo Through Eternity」"
artist = "Evan Call"
date = 2020-10-21
type = "absolute"
catalog = "LACA-9751~3"
tags = ["劇場版「ヴァイオレット・エヴァーガーデン」", "OST"]

[[discs]]
catalog = "LACA-9751"

[[discs.tracks]]
title = "Discovering the Past"
artist = "Evan Call"

[[discs.tracks]]
title = "Generation to Generation"
artist = "Evan Call"

[[discs.tracks]]
title = "The Legacy of Violet Evergarden"
artist = "Evan Call"

[[discs.tracks]]
title = "Hymn to the Sea Pt. 1"
artist = "Evan Call"

[[discs.tracks]]
title = "Some Scars Never Fade"
artist = "Evan Call"

[[discs.tracks]]
title = "Sometimes Dreams Come True"
artist = "Evan Call"

[[discs.tracks]]
title = "On That Fateful Night"
artist = "Evan Call"

[[discs.tracks]]
title = "Dear Gilbert"
artist = "Evan Call"

[[discs.tracks]]
title = "Though Times May Change"
artist = "Evan Call"

[[discs.tracks]]
title = "Bonded by Tragedy"
artist = "Evan Call"

[[discs.tracks]]
title = "Another Voice Calls Out"
artist = "Evan Call"

[[discs.tracks]]
title = "A Young Boy's Hope"
artist = "Evan Call"

[[discs.tracks]]
title = "Complicated Feelings"
artist = "Evan Call"

[[discs.tracks]]
title = "Brotherhood"
artist = "Evan Call"

[[discs.tracks]]
title = "Violet's Promise"
artist = "Evan Call"

[[discs.tracks]]
title = "Yuris' Confession"
artist = "Evan Call"

[[discs.tracks]]
title = "Hodgins' Request"
artist = "Evan Call"

[[discs.tracks]]
title = "As the Days Pass Us By"
artist = "Evan Call"

[[discs.tracks]]
title = "Hymn to the Sea Pt. 2"
artist = "Evan Call"

[[discs.tracks]]
title = "Beyond These Waves"
artist = "Evan Call"

[[discs.tracks]]
title = "After All These Years"
artist = "Evan Call"

[[discs.tracks]]
title = "The Hardships of Gilbert Bougainvillea"
artist = "Evan Call"

[[discs.tracks]]
title = "The Heart Quivers"
artist = "Evan Call"

[[discs.tracks]]
title = "Tears in the Rain"
artist = "Evan Call"

[[discs.tracks]]
title = "Her Soul Yearns"
artist = "Evan Call"

[[discs.tracks]]
title = "A Young Boy's Last Wish"
artist = "Evan Call"

[[discs.tracks]]
title = "His Final Breath"
artist = "Evan Call"

[[discs.tracks]]
title = "Live on for Me"
artist = "Evan Call"

[[discs.tracks]]
title = "After the Storm Comes a New Day"
artist = "Evan Call"

[[discs.tracks]]
title = "Violet's Final Letter"
artist = "Evan Call"

[[discs.tracks]]
title = "Michishirube ~Movie Version~"
artist = "茅原実里"

[[discs.tracks]]
title = "Echo Through Eternity"
artist = "Evan Call"

[[discs.tracks]]
title = "Her Spirit Lives On"
artist = "Evan Call"

[[discs.tracks]]
title = "WILL ~Movie Version~"
artist = "TRUE"

[[discs.tracks]]
title = "To Future People ~Movie Version~"
artist = "TRUE"

[[discs]]
catalog = "LACA-9752"

[[discs.tracks]]
title = "Violet and Isabella"
artist = "Evan Call"

[[discs.tracks]]
title = "A New Era Begins"
artist = "Evan Call"

[[discs.tracks]]
title = "No Matter How Far"
artist = "Evan Call"

[[discs.tracks]]
title = "A Bond Between Sisters"
artist = "Evan Call"

[[discs.tracks]]
title = "Debutante Waltz"
artist = "Evan Call"

[[discs.tracks]]
title = "Debutante Waltz for Piano"
artist = "Evan Call"

[[discs]]
catalog = "LACA-9753"

[[discs.tracks]]
title = "Fountain of Life (Aria by Irma Fliech)"
artist = "TRUE"

[[discs.tracks]]
title = "Hail Leidenschaftlich!"
artist = "Evan Call"

[[discs.tracks]]
title = "Automemories Doll Typing School"
artist = "Evan Call"

[[discs.tracks]]
title = "The Spirit of Kazalli"
artist = "Evan Call"

[[discs.tracks]]
title = "Kingdom of Drossel Wedding March"
artist = "Evan Call"

[[discs.tracks]]
title = "Sunrise at the Shahar Observatory"
artist = "Evan Call"

[[discs.tracks]]
title = "Oscar's Story"
artist = "Evan Call"

[[discs.tracks]]
title = "For the Land That I Come From (Ctrigall Drinking Song)"
artist = "Evan Call"

[[discs.tracks]]
title = "Leiden Airshow Opening Ceremony"
artist = "Evan Call"

[[discs.tracks]]
title = "Softly Sing to Me (Magnolia Family Lullaby)"
artist = "結城アイラ"
