[album]
album_id = "f8641b17-20ca-4589-a2dd-bf306e3ea723"
title = "WILL"
artist = "TRUE"
date = 2020-09-16
type = "normal"
catalog = "LACM-14994"
tags = ["劇場版「ヴァイオレット・エヴァーガーデン」", "ED"]

[[discs]]
catalog = "LACM-14994"

[[discs.tracks]]
title = "WILL"
artist = "TRUE"

[[discs.tracks]]
title = "未来のひとへ ～Orchestra ver.～"
artist = "TRUE"

[[discs.tracks]]
title = "WILL ～English ver.～"
artist = "TRUE"

[[discs.tracks]]
title = "WILL (Instrumental)"
artist = "TRUE"
type = "instrumental"

[[discs.tracks]]
title = "未来のひとへ ～Orchestra ver.～ (Instrumental)"
artist = "TRUE"
type = "instrumental"
