[album]
album_id = "64600c4a-8b4f-4719-bd30-3fa77cec552e"
title = "Prover / Tell me"
artist = "milet"
date = 2020-02-17
type = "normal"
catalog = "SECL-2537"
tags = ["TVアニメ「Fate/Grand Order -絶対魔獣戦線バビロニア-」"]

[[discs]]
catalog = "SECL-2537"

[[discs.tracks]]
title = "Prover"
artist = "milet"
tags = ["ED"]

[[discs.tracks]]
title = "Tell me"
artist = "milet"

[[discs.tracks]]
title = "Your Light"
artist = "milet"

[[discs.tracks]]
title = "レッドネオン"
artist = "milet"
